### ISSUE TITLE
Save autocalculated values as node data in tiles

### ISSUE THREAD

**Issue by adamlodge** [fargeo/sfport-pkg#42]

**Comment by adamlodge** [comment]
Nodes that need to be autopoulated:
- Remaining Balance
- Encumberances and commitments
- Contingency
- Percentage of Contingency Used
- Number Completed Mitigations
- Number of Mitigations
- Number of Mitigations Pending

**Comment by adamlodge** [comment]
meets reqt

**Comment by adamlodge** [comment]
@apeters As far as I can tell it's not working.  I cant find the calc'ed values in the tiles table and I cant seem to search on them.  Do I need to pull more than just the latest package?

**Comment by apeters** [comment]
Right now we don't search on numbers (only strings and concepts, dates, and geom).  That's why you can't find it in search.  

Probably why you don't see them in the DB is that you first need to enable the function in the function manager.
<img width="608" alt="Screen Shot 2019-04-05 at 11 14 57 PM" src="https://user-images.githubusercontent.com/823773/55665668-adbf1d80-57f8-11e9-988c-74fc081b07aa.png">

**Comment by adamlodge** [comment]
@apeters thanks for the explanation.  Looks great!
